import { useEffect, useState } from "react";
import { apiCall } from "./utils/api";

export default function Logs() {
  const [logs, setLogs] = useState([]);
  const [content, setContent] = useState("");
  const [editingName, setEditingName] = useState(null);
  const [newName, setNewName] = useState("");
  const [selectedLog, setSelectedLog] = useState(null);

  const loadLogs = async () => {
    const res = await apiCall("logs");
    setLogs(await res.json());
  };

  const viewLog = async (name) => {
    setSelectedLog(name);
    const res = await apiCall(`logs/${name}`);
    const text = await res.text();
    setContent(text.replace(/\\n/g, "\n"));
  };

  const deleteLog = async (name) => {
    if (!window.confirm("Delete this log?")) return;
    await apiCall(`logs/${name}`, {
      method: "DELETE",
    });
    if (selectedLog === name) {
      setContent("");
      setSelectedLog(null);
    }
    loadLogs();
  };

  const startRename = (name) => {
    setEditingName(name);
    // Remove extension for editing
    const nameWithoutExt = name.replace(/\.[^/.]+$/, "");
    setNewName(nameWithoutExt);
  };

  const cancelRename = () => {
    setEditingName(null);
    setNewName("");
  };

  const saveRename = async (oldName) => {
    if (!newName.trim()) {
      alert("Name cannot be empty");
      return;
    }

    try {
      const res = await apiCall(`logs/${oldName}`, {
        method: "PUT",
        body: JSON.stringify({ new_name: newName.trim() }),
      });

      if (!res.ok) {
        const error = await res.json();
        alert(`Error: ${error.detail || "Failed to rename"}`);
        return;
      }

      const data = await res.json();
      setEditingName(null);
      setNewName("");

      // If this was the selected log, update selection
      if (selectedLog === oldName) {
        setSelectedLog(data.new_name);
        viewLog(data.new_name);
      }

      loadLogs();
    } catch (e) {
      alert(`Error: ${e.toString()}`);
    }
  };

  const downloadLog = async (name) => {
    try {
      const res = await apiCall(`logs/${name}?download=true`);
      const blob = await res.blob();
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = name;
      document.body.appendChild(a);
      a.click();
      window.URL.revokeObjectURL(url);
      document.body.removeChild(a);
    } catch (e) {
      alert(`Error downloading file: ${e.toString()}`);
    }
  };

  useEffect(() => {
    loadLogs();
  }, []);

  return (
    <section className="card">
      <div className="card-header">
        <div>
          <h3 className="card-title">Execution logs</h3>
          <p className="card-subtitle">
            Inspect and prune logs generated by bulk and router operations.
          </p>
        </div>
      </div>

      <div className="two-column-layout">
        <div>
          <ul className="list">
            {logs.map((l) => (
              <li key={l} style={{ marginBottom: 4 }}>
                {editingName === l ? (
                  <div
                    className="card"
                    style={{
                      padding: 8,
                      display: "flex",
                      gap: 6,
                      alignItems: "center",
                    }}
                  >
                    <input
                      className="input"
                      style={{ flex: 1, fontSize: 12 }}
                      value={newName}
                      onChange={(e) => setNewName(e.target.value)}
                      onKeyDown={(e) => {
                        if (e.key === "Enter") saveRename(l);
                        if (e.key === "Escape") cancelRename();
                      }}
                      autoFocus
                    />
                    <button
                      type="button"
                      className="button button--primary button--sm"
                      onClick={() => saveRename(l)}
                    >
                      ✓
                    </button>
                    <button
                      type="button"
                      className="button button--ghost button--sm"
                      onClick={cancelRename}
                    >
                      ✕
                    </button>
                  </div>
                ) : (
                  <button
                    type="button"
                    className="list-item-button"
                    onClick={() => viewLog(l)}
                  >
                    <span style={{ flex: 1, textAlign: "left" }}>{l}</span>
                    <div style={{ display: "flex", gap: 4 }}>
                      <button
                        type="button"
                        className="button button--ghost button--sm"
                        onClick={(e) => {
                          e.stopPropagation();
                          downloadLog(l);
                        }}
                        title="Download"
                      >
                        ⬇
                      </button>
                      <button
                        type="button"
                        className="button button--ghost button--sm"
                        onClick={(e) => {
                          e.stopPropagation();
                          startRename(l);
                        }}
                        title="Rename"
                      >
                        ✏
                      </button>
                      <button
                        type="button"
                        className="button button--danger button--sm"
                        onClick={(e) => {
                          e.stopPropagation();
                          deleteLog(l);
                        }}
                        title="Delete"
                      >
                        ✕
                      </button>
                    </div>
                  </button>
                )}
              </li>
            ))}
          </ul>
        </div>

        <div>
          <div
            style={{
              display: "flex",
              justifyContent: "space-between",
              alignItems: "center",
              marginBottom: 8,
            }}
          >
            <h4 className="card-title" style={{ margin: 0 }}>
              Content
            </h4>
            {selectedLog && (
              <button
                type="button"
                className="button button--ghost button--sm"
                onClick={() => downloadLog(selectedLog)}
              >
                <span className="button-icon">⬇</span>Download
              </button>
            )}
          </div>
          {content ? (
            <pre className="mono-output">{content}</pre>
          ) : (
            <p className="card-subtitle">
              Select a log from the list to view its details.
            </p>
          )}
        </div>
      </div>
    </section>
  );
}
